# Generated by Django 3.2 on 2021-05-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cliente_colaborador_detallepedido_pedido_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.colaborador'),
        ),
    ]
