# Generated by Django 3.2.3 on 2021-06-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210608_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fechaCreacion',
            new_name='fecha_Creacion',
        ),
    ]
