# Generated by Django 3.2.3 on 2021-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_fechacreacion_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechaEntrega',
            field=models.DateField(null=True),
        ),
    ]
