# Generated by Django 3.2.3 on 2021-06-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productoimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='direccionEntrega',
            new_name='direccion_entrega',
        ),
    ]
