# Generated by Django 3.2.3 on 2021-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_direccionentrega_pedido_direccion_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products'),
        ),
    ]
