# Generated by Django 3.2.3 on 2021-06-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_productoimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_colaborador',
            field=models.BooleanField(null=True),
        ),
    ]
