# Generated by Django 3.2.3 on 2021-06-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_profile_is_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_colaborador',
            field=models.BooleanField(default=False),
        ),
    ]
