# Generated by Django 3.2.3 on 2021-06-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profile_is_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_colaborador',
        ),
    ]
