# Generated by Django 3.2.3 on 2021-06-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_profile_is_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_colaborador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='is_colaborador',
            field=models.BooleanField(default=True),
        ),
    ]
