# Generated by Django 3.2.3 on 2021-06-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210617_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fechaCreacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_Creacion',
            new_name='fecha_creacion',
        ),
    ]
